"""empty message

Revision ID: 5205d5269c61
Revises: df12ee91c19c
Create Date: 2020-06-05 12:54:16.654087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5205d5269c61'
down_revision = 'df12ee91c19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'country')
    # ### end Alembic commands ###
