"""empty message

Revision ID: 6543ceb49539
Revises: 96386b18254e
Create Date: 2020-06-04 12:29:30.049923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6543ceb49539'
down_revision = '96386b18254e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'email')
    # ### end Alembic commands ###
